name: linter-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  linter:
    name: check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run liner
        run: make lint
